version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env

    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync
  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db